//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisWebViaje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasajeros
    {
        public string BOLNRO { get; set; }
        public string VIANRO { get; set; }
        public string NOM_PAS { get; set; }
        public Nullable<int> NRO_ASI { get; set; }
        public string TIPO { get; set; }
        public Nullable<decimal> PAGO { get; set; }
    
        public virtual Viaje Viaje { get; set; }
    }
}
